### ISSUE TITLE
Incomplete

### ISSUE THREAD

**Issue by shubhamdamkondwar** [umstek/keystroke-dynamics#1]
is this project complete?
Does it execute efficiently?
Please reply

**Comment by umstek** [comment]
The answer is already in the description of the repository. 
_Biometrics using Keystroke Dynamics coded in Java [hasty/inaccurate/incomplete] (CS3052 Computer Security - Assignment)_

I have used manually assigned constants etc to make it work. But the right way to go would be training a neural network or something akin to that.

**Comment by shubhamdamkondwar** [comment]
can you please complete this project.
I want to try out this project

**Comment by umstek** [comment]
You are free to try it and improve, or build on it. 😄
This project was coded for an assignment and it's complete as far as the assignment is concerned.
