### ISSUE TITLE
Some clearity needed

### ISSUE THREAD

**Issue by rover886** [umstek/keystroke-dynamics#2]
I have gone through this project and it's written very well, only one thing I don't understand about your program is that, why you have used [this formula](https://github.com/umstek/keystroke-dynamics/blob/master/src/lk/umstek/biometrics/keystrokedynamics/features/FeatureMatcher.java#L51)? I want to know what this formula does?

**Comment by umstek** [comment]
Please refer to the last commit 4d3376359b613726761a645907e53ee068093c49. 

You were originally referring to: https://github.com/umstek/keystroke-dynamics/blob/1b7dad43aa83a2d30d0b978dd961a658c1eb681a/src/lk/umstek/biometrics/keystrokedynamics/features/FeatureMatcher.java#L50-L53.
